package tournament;

public enum FIFASoccerTeam
{
	ALGERIA, ANGOLA, ARGENTINA, AUSTRALIA, AUSTRIA,
	BELGIUM, BOLIVIA, BOSNIA_HERZEGOVINA, BRAZIL, BULGARIA,
	CAMEROON, CANADA, CHILE, CHINA, COLOMBIA,
	CONGO, COSTA_RICA, CROATIA, CUBA, CZECH_REPUBLIC,
	DENMARK, ECUADOR, EGYPT, EL_SALVADOR, ENGLAND,
	FRANCE, GERMAN_DR, GERMANY, GHANA, GREECE,
	HAITI, HONDURAS, HUNGARY, INDONESIA, IRAN,
	IRAQ, ISRAEL, ITALY, IVORY_COAST, JAMAICA,
	JAPAN, KOREA_DPR, KOREA_REPUBLIC, KUWAIT, MEXICO,
	MOROCCO, NETHERLANDS, NEW_ZEALAND, NIGERIA, NORTHERN_IRELAND,
	NORWAY, PARAGUAY, PERU, POLAND, PORTUGAL, 
	REPUBLIC_OF_IRELAND, ROMANIA, RUSSIA, SAUDI_ARABIA, SCOTLAND,
	SENEGAL, SERBIA, SLOVAKIA, SLOVENIA, SOUTH_AFRICA,
	SPAIN, SWEDEN, SWITZERLAND, TOGO, TRINIDAD_AND_TOBAGO,
	TUNISIA, TURKEY, UKRAINE, UNITED_ARAB_EMIRATES, URUGUAY,
	USA, WALES;
}